#!/bin/bash
#Set the root password as root if not set as an ENV variable
export PASSWD=${PASSWD:=newine!}
#Set the root password
echo "root:$PASSWD" | chpasswd
#Spawn dropbear
dropbear -E -F &
echo BB-I2C1 > /sys/devices/platform/bone_capemgr/slots

chmod a+rw /dev/i2c-1
daemon --chdir=/app --output=/data/thin.log -- /usr/bin/ruby run.rb
daemon --respawn --chdir=/app --output=/data/nfc.log -- /usr/bin/rake2.1 nfc:work

#Starts cron
sudo service cron start
crontab /etc/cron.d/newine_cron

#Sets time from external RTC module if no internet connection is present
bash rtc

while true; do sleep 1; done
